sudo: required
language: generic 

services:
    - docker

before_install:
    - docker build -t ordaniel/react-test -f ./client/Dockerfile.dev ./client
    
script:
    - docker run -e CI=true ordaniel/react-test npm run test

after_success:
    - docker build -t ordaniel/docker-workshop-multi-client ./client
    - docker build -t ordaniel/docker-workshop-multi-nginx ./nginx
    - docker build -t ordaniel/docker-workshop-multi-server ./server
    - docker build -t ordaniel/docker-workshop-multi-worker ./worker
    #Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker-hub
    - docker push ordaniel/docker-workshop-multi-client
    - docker push ordaniel/docker-workshop-multi-nginx
    - docker push ordaniel/docker-workshop-multi-server
    - docker push ordaniel/docker-workshop-multi-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "milti-docker"
    env: "MultiDocker-env"
    bucket_name: "elasticbeanstalk-us-east-2-985175771782"
    bucket_path: "multi-docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_KEY